### ISSUE TITLE
Question on notification support topcoder challenge

### ISSUE THREAD

**Issue by zmihaf** [topcoder-platform/evernym-api#12]
Hi @kylewu , is this the repo that needs to be updated for the [Evernym - Notifications support in Backend API challenge](https://www.topcoder.com/challenges/35c00e6c-5aa8-4bbc-9313-87f003f2fe0a)? I cant find any clue on the challenge for the existing codebase.

Thank you.

**Comment by kylewu** [comment]
Hi @zmihaf 
the codebase is attached in the forum https://apps.topcoder.com/forums/?module=Thread&threadID=965138&start=0
you should use that codebase.
Thanks!

**Comment by zmihaf** [comment]
Sorry for re opening this @kylewu, but it seems that the forum is empty on my view
![image](https://user-images.githubusercontent.com/5461786/99944461-7c1c1100-2da5-11eb-9dc9-8ea474548435.png)

also I cant open the link you gave 🙏 
![image](https://user-images.githubusercontent.com/5461786/99944508-90f8a480-2da5-11eb-8bef-6829e4fa2c2b.png)
